### ISSUE TITLE
What does distant point cloud registration mean?

### ISSUE THREAD

**Issue by sunyuan789** [liuQuan98/EYOC#3]
感谢你工作的开源，你的工作非常有创造性，但是有几个问题我想问一下。
1.distant point cloud指的是什么。
2.车载激光雷达获得的点云近距离和远距离是刚性的，为什么还需要分远近独立配准？

**Comment by liuQuan98** [comment]
1. Distant point cloud registration指的是配准间距在5至50米范围内的所有点云对。作为对比，传统KITTI上Registration的指的是配准间距刚好为10m的点云对。
2. 因此，并不是现有工作做了近距离，我们工作做了远距离；而是现有工作做了近距离（d=10m），我们远近都行（5<=d<=50m）。以自车的SLAM为下游任务时，当然可以假设两帧间距等于10m；但以多车的相对位姿估计作为下游任务时，我们的问题设定更加实际，不可能要求所有车辆间距都刚好是10m。此外，KITTI上间距10m是一个很简单的评测指标，非常多工作都能拿到98%的配准召回率，看不出差距；而在我们的指标上就能看出不同工作的真正区别。

**Comment by sunyuan789** [comment]
感谢你的回答，我明白了，这项工作非常有实际应用的价值
