### ISSUE TITLE
Direct training parameters

### ISSUE THREAD

**Issue by peakpang** [liuQuan98/EYOC#4]
If I want to train directly on KITTI or another dataset, is it sufficient to modify these two parameters:
--feature_filter "None" \
--spatial_filter "Similarity" \
--filter_radius 40 \
--similarity_thresh 0.6 \
--use_sc2_filtering true \
--pretraining_dataset "waymo" \
Modify==>
--spatial_filter "Spherical" \
\# --pretraining_dataset "waymo" \

**Comment by liuQuan98** [comment]
Theoretically, yes. By removing the similarity-based filter, EYOC no longer loads the similarity map file obtained from WOD. However, please notice that the 'filter_radius' parameter can be sub-optimal for your custom dataset and may require some tuning.
